# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.


# Site Settings
locale                   : "en-US"
title                    : Andrew Nocilly Portfolio
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : Andrew Nocilly
description              : Andrew Nocilly - Projects and CV 
baseurl                  : "/Portfolio" # Set this to your repo name 

# Theme and Style
theme: jekyll-theme-minimal
color_scheme: light # light/default, dark, or aqua

sass:
  style: compressed

# Outputting
permalink: /:categories/:title/

collections:
  pages:
    output: true
  projects:
    output: true
    permalink: /:collection/:path/
  schoolprojects:
    output: true
    permalink: /:collection/:path/

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
